// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtSlLpzVEO2nMvwCJ-kBulhRqWTCzSMeY',
    appId: '1:977220683377:web:bb84f1ea768342e4c67dd0',
    messagingSenderId: '977220683377',
    projectId: 'ssum-scream',
    authDomain: 'ssum-scream.firebaseapp.com',
    storageBucket: 'ssum-scream.firebasestorage.app',
    measurementId: 'G-WCJYF2HTRD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnjaiJGAbot5c39SBz-OQeRvfkwrZBaoo',
    appId: '1:977220683377:android:750eb8221ed537a7c67dd0',
    messagingSenderId: '977220683377',
    projectId: 'ssum-scream',
    storageBucket: 'ssum-scream.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoOF-0GsbZUfmWL8BavJ655rok-1vMhyc',
    appId: '1:977220683377:ios:106c1c0b8476f05ac67dd0',
    messagingSenderId: '977220683377',
    projectId: 'ssum-scream',
    storageBucket: 'ssum-scream.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoOF-0GsbZUfmWL8BavJ655rok-1vMhyc',
    appId: '1:977220683377:ios:106c1c0b8476f05ac67dd0',
    messagingSenderId: '977220683377',
    projectId: 'ssum-scream',
    storageBucket: 'ssum-scream.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtSlLpzVEO2nMvwCJ-kBulhRqWTCzSMeY',
    appId: '1:977220683377:web:9a7df0a30212aeedc67dd0',
    messagingSenderId: '977220683377',
    projectId: 'ssum-scream',
    authDomain: 'ssum-scream.firebaseapp.com',
    storageBucket: 'ssum-scream.firebasestorage.app',
    measurementId: 'G-9Q8VHB4JBK',
  );
}
